
{{- if (include "cloud-pricing-api.postgresql.createExternalSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-pricing-api.postgresql.fullname" . }}-external
  labels:
    {{- include "cloud-pricing-api.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.external.password | b64enc | quote }}
{{- end }}
