apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-pricing-api.fullname" . }}
  labels:
    {{- include "cloud-pricing-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.selfHostedInfracostAPIKey }}
  self-hosted-infracost-api-key: {{ .Values.selfHostedInfracostAPIKey | b64enc | quote }}
  {{- else if not .Values.disableSelfHostedInfracostAPIKey }}
  self-hosted-infracost-api-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.postgresql.enabled) (not .Values.postgresql.existingSecret) -}}
  postgresql-password: {{ .Values.postgresql.external.password | b64enc | quote }}
  {{- end }}
